
server:
  port: 9091

spring:
  datasource:
    url: jdbc:postgresql://172.21.120.71:5432/OneTeamCare_Dev
    driver-class-name: org.postgresql.Driver
    username: gloinc
    password: glodom2009
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

security:
  oauth2:
    resource:
      token-info-uri: http://localhost:9090/oauth/check_token
    client:
      client-id: mobile
      client-secret: pin        